name: "Build and Release"
on: 
  workflow_dispatch:

env:
  NAME_UPPER: PF2
  NAME_LOWER: pf2

jobs:
  export-windows:
    name: Windows Export
    runs-on: windows-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Setup environment
        run: |
          pip install -r requirements.txt
      - name: Generate Localizations
        run: |
          ./GenerateMO.sh
        shell: bash
      - name: Build Windows
        run: |
          ./CompileWindows
      - name: Generate SHA512
        shell: pwsh
        run: |
          Move-Item ./dist/${{ env.NAME_LOWER }}_downloader.exe ${{ env.NAME_UPPER }}DownloaderWindows.exe
          Get-filehash -Algorithm SHA512 ${{ env.NAME_UPPER }}DownloaderWindows.exe > ${{ env.NAME_UPPER }}DownloaderWindows_SHA512
          Compress-Archive -Path ${{ env.NAME_UPPER }}DownloaderWindows.exe -DestinationPath ${{ env.NAME_UPPER }}DownloaderWindows.zip
      - name: dir
        run: |
        dir
        dir dist
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows
          path: |
            path: ${{ env.NAME_UPPER }}DownloaderWindows.zip
            path: ${{ env.NAME_UPPER }}DownloaderWindows_SHA512
          retention-days: 1

  export-linux:
    name: Linux Export
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Setup environment
        run: |
          sudo apt update
          pip install -r requirements.txt
      - name: Generate Localizations
        run: |
          ./GenerateMO.sh
      - name: Build Linux
        run: |
          ./CompileLinux.sh
          mv dist/${{ env.NAME_LOWER}}_downloader ${{ env.NAME_UPPER }}DownloaderLinux
      - name: Generate SHA512
        run: |
          sha512sum ${{ env.NAME_UPPER }}DownloaderLinux >${{ env.NAME_UPPER }}DownloaderLinux_SHA512
      - name: Zip Application
        run: |
          zip ${{ env.NAME_UPPER }}DownloaderLinux.zip ${{ env.NAME_UPPER }}DownloaderLinux
      - name: dir
        run: |
        ls
        ls dist
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux
          path: |
            path: ${{ env.NAME_UPPER }}DownloaderLinux.zip
            path: ${{ env.NAME_UPPER }}DownloaderLinux_SHA512
          retention-days: 1

  release-builds:
    needs: [export-linux, export-windows]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: Download Linux Installer
        uses: actions/download-artifact@v4
      - name: Release Draft
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          name: ${{ env.NAME_UPPER }} Downloader
          files: ${{ env.NAME_UPPER }}Downloader*
          generate_release_notes: true
          tag_name: test
          make_latest: "true"