name: "Build and Release"
on: 
  workflow_dispatch:

env:
  NAME_UPPER: PF2
  NAME_LOWER: pf2

jobs:
  export-windows:
    name: Windows Export
    runs-on: windows-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Setup Environment
        run: |
          pip install -r requirements.txt
      - name: Generate Localizations
        run: |
          ./GenerateMO.sh
        shell: bash
      - name: Build Windows
        run: |
          ./CompileWindows
      - name: Move Binary
        shell: pwsh
        run: |
          Move-Item ./dist/${{ env.NAME_LOWER }}_downloader.exe ${{ env.NAME_UPPER }}DownloaderWindows.exe
      - name: Generate SHA512
        shell: pwsh
        run: |
          (Get-FileHash ${{ env.NAME_UPPER }}DownloaderWindows.exe -Algorithm SHA512).Hash > ${{ env.NAME_UPPER }}DownloaderWindows_SHA512
      - name: Zip Application
        shell: pwsh
        run: |
          Compress-Archive -Path ${{ env.NAME_UPPER }}DownloaderWindows.exe -DestinationPath ${{ env.NAME_UPPER }}DownloaderWindows.zip
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows
          path: |
            ${{ env.NAME_UPPER }}DownloaderWindows_SHA512
            ${{ env.NAME_UPPER }}DownloaderWindows.zip
          retention-days: 1

  export-linux:
    name: Linux Export
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Setup Environment
        run: |
          sudo apt update
          pip install -r requirements.txt
      - name: Generate Localizations
        run: |
          ./GenerateMO.sh
      - name: Build Linux
        run: |
          ./CompileLinux.sh
      - name: Move Binary
        run: |
          mv dist/${{ env.NAME_LOWER}}_downloader ${{ env.NAME_UPPER }}DownloaderLinux
      - name: Generate SHA512
        run: |
          sha512sum ${{ env.NAME_UPPER }}DownloaderLinux > ${{ env.NAME_UPPER }}DownloaderLinux_SHA512
      - name: Zip Application
        run: |
          zip ${{ env.NAME_UPPER }}DownloaderLinux.zip ${{ env.NAME_UPPER }}DownloaderLinux
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux
          path: |
            ${{ env.NAME_UPPER }}DownloaderLinux_SHA512
            ${{ env.NAME_UPPER }}DownloaderLinux.zip
          retention-days: 1

  release-builds:
    name: Release Draft
    needs: [export-linux, export-windows]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download Artifacts
        uses: actions/download-artifact@v4
      - name: Get Current Date
        run: echo "DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
      - name: Release Draft
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          name: ${{ env.NAME_UPPER }}Downloader ${{ env.DATE }} 
          files: |
            */${{ env.NAME_UPPER }}Downloader*
          generate_release_notes: true
          tag_name: ${{ env.DATE }}
          make_latest: true
      