name: "PF2 Build"
on: 
  workflow_dispatch:

jobs:
  export-windows:
    name: Windows Export
    runs-on: windows-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Setup environment
        run: |
          pip install -r requirements.txt
      - name: Generate Localizations
        run: |
          ./GenerateMO.sh
        shell: bash
      - name: Build Windows
        run: |
          ./CompileWindows
      - name: Generate SHA512
        shell: pwsh
        run: |
          Move-Item ./dist/pf2_downloader.exe PF2DownloaderWindows.exe
          Get-filehash -Algorithm SHA512 PF2DownloaderWindows.exe > PF2DownloaderWindows_SHA512
          Compress-Archive -Path PF2DownloaderWindows.exe -DestinationPath PF2DownloaderWindows.zip
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows
          path: |
            path: PF2DownloaderWindows.zip
            path: PF2DownloaderWindows_SHA512
          retention-days: 1

  export-linux:
    name: Linux Export
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Setup environment
        run: |
          sudo apt update
          sudo apt install gettext
          pip install -r requirements.txt
      - name: Build Linux
        run: |
          ./GenerateMO.sh
          ./CompileLinux.sh
          mv dist/pf2_downloader PF2DownloaderLinux
      - name: Generate SHA512
        run: |
          sha512sum PF2DownloaderLinux > PF2DownloaderLinux_SHA512
      - name: Zip Application
        run: |
          zip PF2DownloaderLinux.zip PF2DownloaderLinux
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux
          path: |
            path: PF2DownloaderLinux.zip
            path: PF2DownloaderLinux_SHA512
          retention-days: 1

  release-builds:
    needs: [export-linux, export-windows]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: Download Linux Installer
        uses: actions/download-artifact@v4
      - name: Release Draft
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          name: PF2 Downloader
          files: PF2Downloader*
          generate_release_notes: true
          tag_name: test
          make_latest: "true"